// Vertalingen bezoekerskant. Sleutel = Nederlandse brontekst; waarde = vertaling.
// Ontbreekt een sleutel, dan valt de app terug op het Nederlands.

export const FR: Record<string, string> = {
  "Spaar punten op de kermis": "Gagne des points à la foire",
  "Verzamel punten bij elk kraam, volg de kermissen in je buurt en spaar naar prijzen. Helemaal gratis.": "Gagne des points à chaque stand, suis les foires près de chez toi et économise pour des prix. Entièrement gratuit.",
  "Spaar punten bij elk kraam dat je bezoekt": "Gagne des points à chaque stand que tu visites",
  "Volg de kermissen bij jou in de buurt": "Suis les foires près de chez toi",
  "Spaar naar de hoofdprijs van je favoriete kraam": "Économise pour le gros lot de ton stand préféré",
  "Maak een gratis account": "Créer un compte gratuit",
  "Ik heb al een account · Aanmelden": "J'ai déjà un compte · Se connecter",
  "Werk je op de foor?": "Tu travailles à la foire ?",
  "Uitbater": "Exploitant",
  "Foorkramer": "Forain",
  "Management": "Management",
  "Funpoints · voor de foor": "Funpoints · pour la foire",
  "‹ Terug": "‹ Retour",
  "Account aanmaken": "Créer un compte",
  "Je spaarkaart wordt meteen aan je account gekoppeld — je punten gaan mee.": "Ta carte est directement liée à ton compte — tes points sont conservés.",
  "Maak je gratis Funpoints-account aan en spaar punten bij elke aangesloten kraam.": "Crée ton compte Funpoints gratuit et gagne des points à chaque stand participant.",
  "Voornaam": "Prénom",
  "Achternaam": "Nom",
  "Gebruikersnaam": "Nom d'utilisateur",
  "bv. kermiskoning": "ex. roidelafoire",
  "Hiermee vinden vrienden je. 3–20 tekens: letters, cijfers of _.": "Tes amis te retrouvent ainsi. 3–20 caractères : lettres, chiffres ou _.",
  "E-mail": "E-mail",
  "Geboortedatum": "Date de naissance",
  "Postcode": "Code postal",
  "Wachtwoord": "Mot de passe",
  "minstens 6 tekens": "au moins 6 caractères",
  "Heb je al een account? Inloggen": "Tu as déjà un compte ? Se connecter",
  "Vul je voornaam in.": "Entre ton prénom.",
  "Vul je achternaam in.": "Entre ton nom.",
  "Kies een gebruikersnaam van 3–20 tekens (letters, cijfers of _).": "Choisis un nom d'utilisateur de 3 à 20 caractères (lettres, chiffres ou _).",
  "Kies je geboortedatum.": "Choisis ta date de naissance.",
  "Controleer je geboortedatum.": "Vérifie ta date de naissance.",
  "Je moet minstens 13 jaar zijn om zelf een account te maken. Vraag een ouder om je te helpen.": "Tu dois avoir au moins 13 ans pour créer un compte toi-même. Demande de l'aide à un parent.",
  "Geef een geldige postcode (4 cijfers).": "Entre un code postal valide (4 chiffres).",
  "Vul je e-mailadres in.": "Entre ton adresse e-mail.",
  "Kies een wachtwoord van minstens 6 tekens.": "Choisis un mot de passe d'au moins 6 caractères.",
  "Die gebruikersnaam is al bezet, kies een andere.": "Ce nom d'utilisateur est déjà pris, choisis-en un autre.",
  "Dit e-mailadres heeft al een account.": "Cette adresse e-mail a déjà un compte.",
  "Registreren mislukt. Controleer je e-mailadres.": "Échec de l'inscription. Vérifie ton adresse e-mail.",
  "Account aangemaakt, maar e-mailbevestiging staat nog aan in Supabase.": "Compte créé, mais la confirmation par e-mail est encore activée dans Supabase.",
  "Die gebruikersnaam is net bezet geraakt, kies een andere.": "Ce nom d'utilisateur vient d'être pris, choisis-en un autre.",
  "Account gemaakt, maar je profiel opslaan mislukte. Probeer opnieuw.": "Compte créé, mais l'enregistrement du profil a échoué. Réessaie."
}

export const EN: Record<string, string> = {
  "Spaar punten op de kermis": "Earn points at the fair",
  "Verzamel punten bij elk kraam, volg de kermissen in je buurt en spaar naar prijzen. Helemaal gratis.": "Collect points at every stall, follow the fairs near you and save up for prizes. Completely free.",
  "Spaar punten bij elk kraam dat je bezoekt": "Earn points at every stall you visit",
  "Volg de kermissen bij jou in de buurt": "Follow the fairs near you",
  "Spaar naar de hoofdprijs van je favoriete kraam": "Save up for the top prize at your favourite stall",
  "Maak een gratis account": "Create a free account",
  "Ik heb al een account · Aanmelden": "I already have an account · Sign in",
  "Werk je op de foor?": "Do you work at the fair?",
  "Uitbater": "Operator",
  "Foorkramer": "Stall staff",
  "Management": "Management",
  "Funpoints · voor de foor": "Funpoints · for the fair",
  "‹ Terug": "‹ Back",
  "Account aanmaken": "Create account",
  "Je spaarkaart wordt meteen aan je account gekoppeld — je punten gaan mee.": "Your card is linked to your account right away — your points come with it.",
  "Maak je gratis Funpoints-account aan en spaar punten bij elke aangesloten kraam.": "Create your free Funpoints account and earn points at every participating stall.",
  "Voornaam": "First name",
  "Achternaam": "Last name",
  "Gebruikersnaam": "Username",
  "bv. kermiskoning": "e.g. fairking",
  "Hiermee vinden vrienden je. 3–20 tekens: letters, cijfers of _.": "This is how friends find you. 3–20 characters: letters, digits or _.",
  "E-mail": "Email",
  "Geboortedatum": "Date of birth",
  "Postcode": "Postal code",
  "Wachtwoord": "Password",
  "minstens 6 tekens": "at least 6 characters",
  "Heb je al een account? Inloggen": "Already have an account? Sign in",
  "Vul je voornaam in.": "Enter your first name.",
  "Vul je achternaam in.": "Enter your last name.",
  "Kies een gebruikersnaam van 3–20 tekens (letters, cijfers of _).": "Choose a username of 3–20 characters (letters, digits or _).",
  "Kies je geboortedatum.": "Choose your date of birth.",
  "Controleer je geboortedatum.": "Check your date of birth.",
  "Je moet minstens 13 jaar zijn om zelf een account te maken. Vraag een ouder om je te helpen.": "You must be at least 13 to create an account yourself. Ask a parent to help you.",
  "Geef een geldige postcode (4 cijfers).": "Enter a valid postal code (4 digits).",
  "Vul je e-mailadres in.": "Enter your email address.",
  "Kies een wachtwoord van minstens 6 tekens.": "Choose a password of at least 6 characters.",
  "Die gebruikersnaam is al bezet, kies een andere.": "That username is taken, choose another.",
  "Dit e-mailadres heeft al een account.": "This email already has an account.",
  "Registreren mislukt. Controleer je e-mailadres.": "Registration failed. Check your email address.",
  "Account aangemaakt, maar e-mailbevestiging staat nog aan in Supabase.": "Account created, but email confirmation is still enabled in Supabase.",
  "Die gebruikersnaam is net bezet geraakt, kies een andere.": "That username was just taken, choose another.",
  "Account gemaakt, maar je profiel opslaan mislukte. Probeer opnieuw.": "Account created, but saving your profile failed. Please try again."
}
