// Vertalingen bezoekerskant. Sleutel = Nederlandse brontekst; waarde = vertaling.
// Ontbreekt een sleutel, dan valt de app terug op het Nederlands.

export const FR: Record<string, string> = {
  "Spaar punten op de kermis": "Gagne des points à la foire",
  "Verzamel punten bij elk kraam, volg de kermissen in je buurt en spaar naar prijzen. Helemaal gratis.": "Gagne des points à chaque stand, suis les foires près de chez toi et économise pour des prix. Entièrement gratuit.",
  "Spaar punten bij elk kraam dat je bezoekt": "Gagne des points à chaque stand que tu visites",
  "Volg de kermissen bij jou in de buurt": "Suis les foires près de chez toi",
  "Spaar naar de hoofdprijs van je favoriete kraam": "Économise pour le gros lot de ton stand préféré",
  "Maak een gratis account": "Créer un compte gratuit",
  "Ik heb al een account · Aanmelden": "J'ai déjà un compte · Se connecter",
  "Werk je op de foor?": "Tu travailles à la foire ?",
  "Uitbater": "Exploitant",
  "Foorkramer": "Forain",
  "Management": "Management",
  "Funpoints · voor de foor": "Funpoints · pour la foire",
  "‹ Terug": "‹ Retour",
  "Account aanmaken": "Créer un compte",
  "Je spaarkaart wordt meteen aan je account gekoppeld — je punten gaan mee.": "Ta carte est directement liée à ton compte — tes points sont conservés.",
  "Maak je gratis Funpoints-account aan en spaar punten bij elke aangesloten kraam.": "Crée ton compte Funpoints gratuit et gagne des points à chaque stand participant.",
  "Voornaam": "Prénom",
  "Achternaam": "Nom",
  "Gebruikersnaam": "Nom d'utilisateur",
  "bv. kermiskoning": "ex. roidelafoire",
  "Hiermee vinden vrienden je. 3–20 tekens: letters, cijfers of _.": "Tes amis te retrouvent ainsi. 3–20 caractères : lettres, chiffres ou _.",
  "E-mail": "E-mail",
  "Geboortedatum": "Date de naissance",
  "Postcode": "Code postal",
  "Wachtwoord": "Mot de passe",
  "minstens 6 tekens": "au moins 6 caractères",
  "Heb je al een account? Inloggen": "Tu as déjà un compte ? Se connecter",
  "Vul je voornaam in.": "Entre ton prénom.",
  "Vul je achternaam in.": "Entre ton nom.",
  "Kies een gebruikersnaam van 3–20 tekens (letters, cijfers of _).": "Choisis un nom d'utilisateur de 3 à 20 caractères (lettres, chiffres ou _).",
  "Kies je geboortedatum.": "Choisis ta date de naissance.",
  "Controleer je geboortedatum.": "Vérifie ta date de naissance.",
  "Je moet minstens 13 jaar zijn om zelf een account te maken. Vraag een ouder om je te helpen.": "Tu dois avoir au moins 13 ans pour créer un compte toi-même. Demande de l'aide à un parent.",
  "Geef een geldige postcode (4 cijfers).": "Entre un code postal valide (4 chiffres).",
  "Vul je e-mailadres in.": "Entre ton adresse e-mail.",
  "Kies een wachtwoord van minstens 6 tekens.": "Choisis un mot de passe d'au moins 6 caractères.",
  "Die gebruikersnaam is al bezet, kies een andere.": "Ce nom d'utilisateur est déjà pris, choisis-en un autre.",
  "Dit e-mailadres heeft al een account.": "Cette adresse e-mail a déjà un compte.",
  "Registreren mislukt. Controleer je e-mailadres.": "Échec de l'inscription. Vérifie ton adresse e-mail.",
  "Account aangemaakt, maar e-mailbevestiging staat nog aan in Supabase.": "Compte créé, mais la confirmation par e-mail est encore activée dans Supabase.",
  "Die gebruikersnaam is net bezet geraakt, kies een andere.": "Ce nom d'utilisateur vient d'être pris, choisis-en un autre.",
  "Account gemaakt, maar je profiel opslaan mislukte. Probeer opnieuw.": "Compte créé, mais l'enregistrement du profil a échoué. Réessaie.",
  "Bezoeker": "Visiteur",
  "Log in om je kermis-belevenis te openen.": "Connecte-toi pour ouvrir ton expérience de foire.",
  "Inloggen mislukt — controleer je e-mail en wachtwoord.": "Échec de la connexion — vérifie ton e-mail et ton mot de passe.",
  "Inloggen": "Se connecter",
  "Heb je een Funpoints-kaartje? Scan de achterkant bij het registreren om je punten mee te nemen.": "Tu as une carte Funpoints ? Scanne le dos lors de l'inscription pour récupérer tes points.",
  "Deze login is geen bezoeker-account. Log uit en registreer je, of log in met je bezoeker-account.": "Cet identifiant n'est pas un compte visiteur. Déconnecte-toi et inscris-toi, ou connecte-toi avec ton compte visiteur.",
  "Uitloggen": "Se déconnecter",
  "Home": "Accueil",
  "Kermissen": "Foires",
  "Saldo": "Solde",
  "Vrienden": "Amis",
  "Hallo": "Salut",
  "Klaar voor wat kermisplezier?": "Prêt pour un peu de fun à la foire ?",
  "bezocht": "visités",
  "punten": "points",
  "gevolgd": "suivis",
  "Kramen": "Stands",
  "Volg je favorieten": "Suis tes favoris",
  "Tradities": "Traditions",
  "Je jaarlijkse streaks": "Tes séries annuelles",
  "🔔 Meldingen staan uit in je browser — zet ze aan bij de site-instellingen": "🔔 Les notifications sont désactivées dans ton navigateur — active-les dans les paramètres du site",
  "🔔 Zet meldingen aan en mis geen enkele actie in je buurt": "🔔 Active les notifications et ne rate aucune promo près de chez toi",
  "Aanzetten": "Activer",
  "⭐ SUPERSTER-ACTIE": "⭐ PROMO SUPERSTAR",
  "❤️ Favorieten in de buurt": "❤️ Favoris près de chez toi",
  "🟢 Nu op {kermis}": "🟢 À {kermis} en ce moment",
  "📍 Binnenkort · {kermis}": "📍 Bientôt · {kermis}",
  "🔥 Deze week": "🔥 Cette semaine",
  "🔥 Acties & deals": "🔥 Promos & deals",
  "🟢 Nu open": "🟢 Ouvert",
  "Binnenkort": "Bientôt",
  "📍 regio": "📍 région",
  "kraam": "stand",
  "kramen": "stands",
  "⭐ UITGELICHT": "⭐ EN VEDETTE",
  "🎟️ Tik om je voucher op te halen": "🎟️ Touche pour obtenir ton bon",
  "voucher": "bon",
  "Levels": "Niveaux",
  "Ontdekker": "Explorateur",
  "Kermisganger": "Habitué de la foire",
  "check-ins": "check-ins",
  "Level {lvl}": "Niveau {lvl}",
  "Nog {n} {eenheid} tot level {lvl}": "Encore {n} {eenheid} jusqu'au niveau {lvl}",
  "🎟️ Mijn QR": "🎟️ Mon QR",
  "QR wordt geladen…": "Chargement du QR…",
  "Jouw punten-QR": "Ton QR de points",
  "Toon deze ene QR aan elk kraam. De foorkramer scant hem en je punten worden automatisch bij dàt kraam bijgeschreven of ingeruild — nooit door elkaar.": "Montre ce QR unique à chaque stand. Le forain le scanne et tes points sont automatiquement crédités ou échangés à ce stand — jamais mélangés.",
  "📴 Geen internet — je QR werkt gewoon. Je punten verschijnen zodra je terug online bent.": "📴 Pas d'internet — ton QR fonctionne quand même. Tes points apparaissent dès que tu es de nouveau en ligne.",
  "⭐ Mijn saldo's": "⭐ Mes soldes",
  "Je saldo per kraam": "Ton solde par stand",
  "🎁 Bekijk je prijs-voortgang ›": "🎁 Vois ta progression vers le prix ›",
  "Je hebt nog geen punten gespaard. Laat je QR scannen bij een kraam om te beginnen.": "Tu n'as pas encore de points. Fais scanner ton QR à un stand pour commencer.",
  "Funpoints · meer belevenis komt eraan 🎠": "Funpoints · encore plus d'expériences à venir 🎠",
  "👤 Account": "👤 Compte",
  "Profiel": "Profil",
  "Naam": "Nom",
  "Je naam": "Ton nom",
  "Zo vinden vrienden je. 3–20 tekens: letters, cijfers of _.": "Tes amis te retrouvent ainsi. 3–20 caractères : lettres, chiffres ou _.",
  "Zo tonen we je kermissen en acties in je buurt.": "Ainsi nous te montrons les foires et promos près de chez toi.",
  "Account verwijderen mislukt. Probeer later opnieuw.": "Échec de la suppression du compte. Réessaie plus tard.",
  "Gebruikersnaam: 3–20 tekens, enkel letters, cijfers en _.": "Nom d'utilisateur : 3–20 caractères, uniquement lettres, chiffres et _.",
  "Die gebruikersnaam is al bezet.": "Ce nom d'utilisateur est déjà pris.",
  "Gebruikersnaam ongeldig.": "Nom d'utilisateur invalide.",
  "Opslaan mislukt. Probeer opnieuw.": "Échec de l'enregistrement. Réessaie.",
  "Opgeslagen ✓": "Enregistré ✓",
  "Opslaan": "Enregistrer",
  "Meldingen": "Notifications",
  "Pushmeldingen": "Notifications push",
  "Een seintje bij nieuwe acties in je buurt.": "Un petit signal lors de nouvelles promos près de chez toi.",
  "Aan": "Activé",
  "Geblokkeerd": "Bloqué",
  "Uit": "Désactivé",
  "Meldingen werken in de Funpoints-app op je beginscherm (voeg de site toe via ‘Zet op beginscherm’).": "Les notifications fonctionnent dans l'app Funpoints sur ton écran d'accueil (ajoute le site via « Sur l'écran d'accueil »).",
  "Pushmeldingen komen binnenkort in de app.": "Les notifications push arrivent bientôt dans l'app.",
  "Account": "Compte",
  "Account verwijderen": "Supprimer le compte",
  "Weet je het zeker? Je account, je gespaarde punten en al je gegevens worden definitief verwijderd. Dit kan niet ongedaan gemaakt worden.": "Tu es sûr ? Ton compte, tes points épargnés et toutes tes données seront définitivement supprimés. C'est irréversible.",
  "Annuleren": "Annuler",
  "Definitief verwijderen": "Supprimer définitivement",
  "Al ingewisseld": "Déjà échangé",
  "op": "le",
  "Toon deze QR aan de foorkramer. Hij kan hem één keer scannen.": "Montre ce QR au forain. Il peut le scanner une seule fois.",
  "Voucher ophalen mislukt. Probeer straks opnieuw.": "Échec de la récupération du bon. Réessaie plus tard.",
  "Sluiten": "Fermer",
  "jan": "janv",
  "feb": "févr",
  "mrt": "mars",
  "apr": "avr",
  "mei": "mai",
  "jun": "juin",
  "jul": "juil",
  "aug": "août",
  "sep": "sept",
  "okt": "oct",
  "nov": "nov",
  "dec": "déc",
  "🎡 Kermis-kalender": "🎡 Calendrier des foires",
  "BIJ JOU IN DE BUURT": "PRÈS DE CHEZ TOI",
  "ALLE KERMISSEN": "TOUTES LES FOIRES",
  "{n} kermissen in {jaar}": "{n} foires en {jaar}",
  "{n} de komende 30 dagen": "{n} dans les 30 prochains jours",
  "Heel België": "Toute la Belgique",
  "📍 In mijn regio": "📍 Dans ma région",
  "🟢 Nu actief": "🟢 En cours",
  "Later": "Plus tard",
  "Voorbij": "Passé",
  "Geen kermissen in deze categorie.": "Aucune foire dans cette catégorie.",
  "Geen kermissen in deze categorie in jouw regio.": "Aucune foire dans cette catégorie dans ta région.",
  "📍 In jouw regio": "📍 Dans ta région",
  "die je volgt": "que tu suis",
  "Bezoeken": "Visites",
  "Deze maand": "Ce mois",
  "kermissen": "foires",
  "deze maand": "ce mois",
  "vriend": "ami",
  "vrienden": "amis",
  "👥 Vrienden": "👥 Amis",
  "VOLG JE VRIENDEN": "SUIS TES AMIS",
  "Vergelijk jullie streaks en klim in de ranglijst.": "Compare vos séries et grimpe dans le classement.",
  "Vriend toevoegen": "Ajouter un ami",
  "Zoek iemand op zijn gebruikersnaam.": "Cherche quelqu'un par son nom d'utilisateur.",
  "gebruikersnaam": "nom d'utilisateur",
  "Zoek": "Chercher",
  "+ Verzoek": "+ Demande",
  "Geen bezoeker met die gebruikersnaam gevonden.": "Aucun visiteur trouvé avec ce nom d'utilisateur.",
  "Jullie zijn al verbonden of er loopt al een verzoek.": "Vous êtes déjà connectés ou une demande est déjà en cours.",
  "Versturen mislukt.": "Échec de l'envoi.",
  "Verzoek verstuurd! 🎉": "Demande envoyée ! 🎉",
  "📨 Verzoeken": "📨 Demandes",
  "wil je vriend worden": "veut devenir ton ami",
  "Aanvaard": "Accepter",
  "🏆 Ranglijst": "🏆 Classement",
  "Voeg vrienden toe om samen een ranglijst te vormen.": "Ajoute des amis pour former un classement ensemble.",
  "Jij": "Toi",
  "Lvl {n}": "Niv {n}",
  "Je vrienden": "Tes amis",
  "Vriend": "Ami"
}

export const EN: Record<string, string> = {
  "Spaar punten op de kermis": "Earn points at the fair",
  "Verzamel punten bij elk kraam, volg de kermissen in je buurt en spaar naar prijzen. Helemaal gratis.": "Collect points at every stall, follow the fairs near you and save up for prizes. Completely free.",
  "Spaar punten bij elk kraam dat je bezoekt": "Earn points at every stall you visit",
  "Volg de kermissen bij jou in de buurt": "Follow the fairs near you",
  "Spaar naar de hoofdprijs van je favoriete kraam": "Save up for the top prize at your favourite stall",
  "Maak een gratis account": "Create a free account",
  "Ik heb al een account · Aanmelden": "I already have an account · Sign in",
  "Werk je op de foor?": "Do you work at the fair?",
  "Uitbater": "Operator",
  "Foorkramer": "Stall staff",
  "Management": "Management",
  "Funpoints · voor de foor": "Funpoints · for the fair",
  "‹ Terug": "‹ Back",
  "Account aanmaken": "Create account",
  "Je spaarkaart wordt meteen aan je account gekoppeld — je punten gaan mee.": "Your card is linked to your account right away — your points come with it.",
  "Maak je gratis Funpoints-account aan en spaar punten bij elke aangesloten kraam.": "Create your free Funpoints account and earn points at every participating stall.",
  "Voornaam": "First name",
  "Achternaam": "Last name",
  "Gebruikersnaam": "Username",
  "bv. kermiskoning": "e.g. fairking",
  "Hiermee vinden vrienden je. 3–20 tekens: letters, cijfers of _.": "This is how friends find you. 3–20 characters: letters, digits or _.",
  "E-mail": "Email",
  "Geboortedatum": "Date of birth",
  "Postcode": "Postal code",
  "Wachtwoord": "Password",
  "minstens 6 tekens": "at least 6 characters",
  "Heb je al een account? Inloggen": "Already have an account? Sign in",
  "Vul je voornaam in.": "Enter your first name.",
  "Vul je achternaam in.": "Enter your last name.",
  "Kies een gebruikersnaam van 3–20 tekens (letters, cijfers of _).": "Choose a username of 3–20 characters (letters, digits or _).",
  "Kies je geboortedatum.": "Choose your date of birth.",
  "Controleer je geboortedatum.": "Check your date of birth.",
  "Je moet minstens 13 jaar zijn om zelf een account te maken. Vraag een ouder om je te helpen.": "You must be at least 13 to create an account yourself. Ask a parent to help you.",
  "Geef een geldige postcode (4 cijfers).": "Enter a valid postal code (4 digits).",
  "Vul je e-mailadres in.": "Enter your email address.",
  "Kies een wachtwoord van minstens 6 tekens.": "Choose a password of at least 6 characters.",
  "Die gebruikersnaam is al bezet, kies een andere.": "That username is taken, choose another.",
  "Dit e-mailadres heeft al een account.": "This email already has an account.",
  "Registreren mislukt. Controleer je e-mailadres.": "Registration failed. Check your email address.",
  "Account aangemaakt, maar e-mailbevestiging staat nog aan in Supabase.": "Account created, but email confirmation is still enabled in Supabase.",
  "Die gebruikersnaam is net bezet geraakt, kies een andere.": "That username was just taken, choose another.",
  "Account gemaakt, maar je profiel opslaan mislukte. Probeer opnieuw.": "Account created, but saving your profile failed. Please try again.",
  "Bezoeker": "Visitor",
  "Log in om je kermis-belevenis te openen.": "Log in to open your fair experience.",
  "Inloggen mislukt — controleer je e-mail en wachtwoord.": "Sign-in failed — check your email and password.",
  "Inloggen": "Sign in",
  "Heb je een Funpoints-kaartje? Scan de achterkant bij het registreren om je punten mee te nemen.": "Got a Funpoints card? Scan the back when registering to bring your points along.",
  "Deze login is geen bezoeker-account. Log uit en registreer je, of log in met je bezoeker-account.": "This login is not a visitor account. Log out and register, or sign in with your visitor account.",
  "Uitloggen": "Log out",
  "Home": "Home",
  "Kermissen": "Fairs",
  "Saldo": "Balance",
  "Vrienden": "Friends",
  "Hallo": "Hi",
  "Klaar voor wat kermisplezier?": "Ready for some fair fun?",
  "bezocht": "visited",
  "punten": "points",
  "gevolgd": "followed",
  "Kramen": "Stalls",
  "Volg je favorieten": "Follow your favourites",
  "Tradities": "Traditions",
  "Je jaarlijkse streaks": "Your yearly streaks",
  "🔔 Meldingen staan uit in je browser — zet ze aan bij de site-instellingen": "🔔 Notifications are off in your browser — turn them on in the site settings",
  "🔔 Zet meldingen aan en mis geen enkele actie in je buurt": "🔔 Turn on notifications and never miss a deal near you",
  "Aanzetten": "Turn on",
  "⭐ SUPERSTER-ACTIE": "⭐ SUPERSTAR DEAL",
  "❤️ Favorieten in de buurt": "❤️ Favourites nearby",
  "🟢 Nu op {kermis}": "🟢 Now at {kermis}",
  "📍 Binnenkort · {kermis}": "📍 Soon · {kermis}",
  "🔥 Deze week": "🔥 This week",
  "🔥 Acties & deals": "🔥 Deals & offers",
  "🟢 Nu open": "🟢 Open now",
  "Binnenkort": "Soon",
  "📍 regio": "📍 region",
  "kraam": "stall",
  "kramen": "stalls",
  "⭐ UITGELICHT": "⭐ FEATURED",
  "🎟️ Tik om je voucher op te halen": "🎟️ Tap to get your voucher",
  "voucher": "voucher",
  "Levels": "Levels",
  "Ontdekker": "Explorer",
  "Kermisganger": "Fairgoer",
  "check-ins": "check-ins",
  "Level {lvl}": "Level {lvl}",
  "Nog {n} {eenheid} tot level {lvl}": "{n} {eenheid} more to level {lvl}",
  "🎟️ Mijn QR": "🎟️ My QR",
  "QR wordt geladen…": "Loading QR…",
  "Jouw punten-QR": "Your points QR",
  "Toon deze ene QR aan elk kraam. De foorkramer scant hem en je punten worden automatisch bij dàt kraam bijgeschreven of ingeruild — nooit door elkaar.": "Show this one QR at every stall. The operator scans it and your points are automatically added or redeemed at that stall — never mixed up.",
  "📴 Geen internet — je QR werkt gewoon. Je punten verschijnen zodra je terug online bent.": "📴 No internet — your QR still works. Your points appear as soon as you're back online.",
  "⭐ Mijn saldo's": "⭐ My balances",
  "Je saldo per kraam": "Your balance per stall",
  "🎁 Bekijk je prijs-voortgang ›": "🎁 See your prize progress ›",
  "Je hebt nog geen punten gespaard. Laat je QR scannen bij een kraam om te beginnen.": "You haven't saved any points yet. Have your QR scanned at a stall to get started.",
  "Funpoints · meer belevenis komt eraan 🎠": "Funpoints · more experiences coming soon 🎠",
  "👤 Account": "👤 Account",
  "Profiel": "Profile",
  "Naam": "Name",
  "Je naam": "Your name",
  "Zo vinden vrienden je. 3–20 tekens: letters, cijfers of _.": "This is how friends find you. 3–20 characters: letters, digits or _.",
  "Zo tonen we je kermissen en acties in je buurt.": "This is how we show you fairs and deals near you.",
  "Account verwijderen mislukt. Probeer later opnieuw.": "Deleting the account failed. Please try again later.",
  "Gebruikersnaam: 3–20 tekens, enkel letters, cijfers en _.": "Username: 3–20 characters, only letters, digits and _.",
  "Die gebruikersnaam is al bezet.": "That username is already taken.",
  "Gebruikersnaam ongeldig.": "Invalid username.",
  "Opslaan mislukt. Probeer opnieuw.": "Saving failed. Please try again.",
  "Opgeslagen ✓": "Saved ✓",
  "Opslaan": "Save",
  "Meldingen": "Notifications",
  "Pushmeldingen": "Push notifications",
  "Een seintje bij nieuwe acties in je buurt.": "A ping when there are new deals near you.",
  "Aan": "On",
  "Geblokkeerd": "Blocked",
  "Uit": "Off",
  "Meldingen werken in de Funpoints-app op je beginscherm (voeg de site toe via ‘Zet op beginscherm’).": "Notifications work in the Funpoints app on your home screen (add the site via \"Add to Home Screen\").",
  "Pushmeldingen komen binnenkort in de app.": "Push notifications are coming soon in the app.",
  "Account": "Account",
  "Account verwijderen": "Delete account",
  "Weet je het zeker? Je account, je gespaarde punten en al je gegevens worden definitief verwijderd. Dit kan niet ongedaan gemaakt worden.": "Are you sure? Your account, your saved points and all your data will be permanently deleted. This cannot be undone.",
  "Annuleren": "Cancel",
  "Definitief verwijderen": "Delete permanently",
  "Al ingewisseld": "Already redeemed",
  "op": "on",
  "Toon deze QR aan de foorkramer. Hij kan hem één keer scannen.": "Show this QR to the operator. They can scan it once.",
  "Voucher ophalen mislukt. Probeer straks opnieuw.": "Getting the voucher failed. Please try again later.",
  "Sluiten": "Close",
  "jan": "Jan",
  "feb": "Feb",
  "mrt": "Mar",
  "apr": "Apr",
  "mei": "May",
  "jun": "Jun",
  "jul": "Jul",
  "aug": "Aug",
  "sep": "Sep",
  "okt": "Oct",
  "nov": "Nov",
  "dec": "Dec",
  "🎡 Kermis-kalender": "🎡 Fair calendar",
  "BIJ JOU IN DE BUURT": "NEAR YOU",
  "ALLE KERMISSEN": "ALL FAIRS",
  "{n} kermissen in {jaar}": "{n} fairs in {jaar}",
  "{n} de komende 30 dagen": "{n} in the next 30 days",
  "Heel België": "All of Belgium",
  "📍 In mijn regio": "📍 In my region",
  "🟢 Nu actief": "🟢 Active now",
  "Later": "Later",
  "Voorbij": "Past",
  "Geen kermissen in deze categorie.": "No fairs in this category.",
  "Geen kermissen in deze categorie in jouw regio.": "No fairs in this category in your region.",
  "📍 In jouw regio": "📍 In your region",
  "die je volgt": "you follow",
  "Bezoeken": "Visits",
  "Deze maand": "This month",
  "kermissen": "fairs",
  "deze maand": "this month",
  "vriend": "friend",
  "vrienden": "friends",
  "👥 Vrienden": "👥 Friends",
  "VOLG JE VRIENDEN": "FOLLOW YOUR FRIENDS",
  "Vergelijk jullie streaks en klim in de ranglijst.": "Compare your streaks and climb the leaderboard.",
  "Vriend toevoegen": "Add a friend",
  "Zoek iemand op zijn gebruikersnaam.": "Find someone by their username.",
  "gebruikersnaam": "username",
  "Zoek": "Search",
  "+ Verzoek": "+ Request",
  "Geen bezoeker met die gebruikersnaam gevonden.": "No visitor found with that username.",
  "Jullie zijn al verbonden of er loopt al een verzoek.": "You're already connected or a request is already pending.",
  "Versturen mislukt.": "Sending failed.",
  "Verzoek verstuurd! 🎉": "Request sent! 🎉",
  "📨 Verzoeken": "📨 Requests",
  "wil je vriend worden": "wants to be your friend",
  "Aanvaard": "Accept",
  "🏆 Ranglijst": "🏆 Leaderboard",
  "Voeg vrienden toe om samen een ranglijst te vormen.": "Add friends to build a leaderboard together.",
  "Jij": "You",
  "Lvl {n}": "Lvl {n}",
  "Je vrienden": "Your friends",
  "Vriend": "Friend"
}
